---
# tasks file for roles/mongodb
- name: Import mongodb keyserver arch x86_64
  sudo: yes
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10
  when: ansible_architecture == "x86_64"

- name: Create a list file and update local pkg database arch x86_64
  sudo: yes
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse' state=present
  when: ansible_architecture == "x86_64"

- name: Install mongodb server i386
  sudo: yes
  apt: name=mongodb state=present update_cache=yes
  when: ansible_architecture != "x86_64"

- name: Install mongodb server arch x86_64
  sudo: yes
  apt: name=mongodb-org state=present update_cache=yes
  when: ansible_architecture == "x86_64"
