---
# tasks file for roles/nodejs
- name: Install commons
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - python-software-properties

- name: Add ppa ad update local pkg database
  sudo: yes
  apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes

- name: Install node
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - npm
